export const CONSTANTS = {
  CURRENCY: 'CBDC_IDR',
  PAGINATION: {
    DEFAULT_LIMIT: 20,
    MAX_LEDGER_LIMIT: 200,
    MAX_TRANSACTION_LIMIT: 50,
  },
  COOLDOWN_SECONDS: 10,
} as const;

export const ROLES = {
  ADMIN: 'CENTRAL_BANK_ADMIN',
  AUDITOR: 'AUDITOR',
  USER: 'WALLET_USER',
  MERCHANT: 'MERCHANT',
  SYSTEM: 'SYSTEM_SERVICE',
} as const;
